version: '3.7'

services:
  rtibot:
    image: rtibot
    build: .
    environment:
      NODE_ENV: development
      RTIBOT_CONFIG: Debug
    ports:
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 dist/App.js
    volumes:
      - type: volume
        source: debugdata
        target: /usr/src/app/data

volumes: 
  debugdata: