version: '3.7'

services:
  rtibot:
    image: rtibot
    build: .
    environment:
      NODE_ENV: production
    volumes:
      - type: volume
        source: proddata
        target: /data

volumes:
  proddata: