import { DMChannel, GroupDMChannel, TextChannel, Snowflake, Client, Guild, CategoryChannel } from "discord.js";
import { IRaidEvent } from "./data/RaidEvent";
import { RaidEventView } from "./RaidEventView";
import { Event } from "../base/Event";
import { PersistentView } from "../base/PersistentView";
import { Util } from "../Util";

/**
 * A text channel dedicated to and event.
 * Contains an embed at the top with event information.
 */
export class RaidEventChannel {
    public static async createInGuild(guild: Guild, category: CategoryChannel, event: IRaidEvent) {
        const channel = await guild.createChannel(Util.toTextChannelName(event.name), {
            parent: category,
            topic: "Auto-generated by bot.",
            type: "text",
        }) as TextChannel;
        const view = new RaidEventView(await PersistentView.createInChannel(channel, "Placeholder."), event);
        view.message.pin();
        return new RaidEventChannel(channel, view);
    }

    public static async fromObj(guild: Guild, obj: object): Promise<RaidEventChannel> {
        const event = obj["event"] as IRaidEvent;
        const channelId = obj["channel"] as Snowflake;
        const messageId = obj["message"] as Snowflake;

        const channel = guild.channels.get(channelId) as TextChannel;
        if (!channel) { throw new Error("Channel not found for " + event.name); }
        const message = await channel.fetchMessage(messageId);
        if (!message) { throw new Error("Message not found for " + event.name); }
        const view = new RaidEventView(new PersistentView(message), event);
        return new RaidEventChannel(channel, view);
    }

    private constructor(private _channel: TextChannel | DMChannel | GroupDMChannel,
                        private eventView: RaidEventView) {
        // TODO: set permissions?
    }

    public get channel(): TextChannel | DMChannel | GroupDMChannel {
        return this._channel;
    }

    public get event(): IRaidEvent {
        return this.eventView.data;
    }

    public get eventChanged(): Event<void> {
        return this.eventView.eventChanged;
    }

    /**
     * Converts this raid channel into a serializable object
     */
    public toObj(): object {
        return {
            channel: this._channel.id,
            event: this.eventView.data,
            message: this.eventView.message.id,
        };
    }
}
